steps:

- name: gcr.io/kaniko-project/executor
  id: Build & Push proxy
  args:
  - --destination=gcr.io/$PROJECT_ID/proxy
  - --cache=true
  - --cache-ttl=6h

- name: gcr.io/kaniko-project/executor
  id: Build & Push TorchServe
  args:
  - --destination=gcr.io/$PROJECT_ID/torch-serve-image
  - --cache=true
  - --cache-ttl=6h

- name: 'gcr.io/cloud-builders/gcloud'
  id: Create cluster
  waitFor:
  - Build & Push proxy
  - Build & Push TorchServe
  entrypoint: /bin/sh
  args:
  - '-c'
  - |
    gcloud container clusters create \
      ${_CLUSTER_NAME} \
      --zone=asia-northeast1-a \
      --num-nodes=1 \
      --no-enable-autoupgrade || true

- name: gcr.io/cloud-builders/gke-deploy
  id: Deploy
  waitFor:
  - Create cluster
  args:
  - run
  - --filename=k8s
  - --location=asia-northeast1-a
  - --cluster=${_CLUSTER_NAME}

timeout: 2400s
