steps:
- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/dev-mlops/proxy', '-f', 'Dockerfile.proxy', '.']
  id: docker build proxy

- name: gcr.io/cloud-builders/docker
  args: ['build', '-t', 'gcr.io/dev-mlops/torch-serve-image', '-f','Dockerfile.torchserve', '.']
  id: docker-build-torchserve

- name: gcr.io/cloud-builders/gcloud
  args: [
    'gcloud', 'container', 'clusters', 'create', '${_CLUSTER_NAME}',
    '--zone=asia-northeast1', '--no-enable-autoupgrade'
    ]
  id: create-cluster

- name: gcr.io/cloud-builders/gke-deploy
  args: ['run', '--filename=k8s', '--location=asia-northeast1', '--cluster=${_CLUSTER_NAME}']
  id: GKE-deploy

images: [
  'gcr.io/dev-mlops/torch-serve-image:${SHORT_SHA}',
  'gcr.io/dev-mlops/proxy-image:${SHORT_SHA}'
  ]
