steps:
- name: 'gcr.io/cloud-builders/docker'
  id: docker-build-proxy
  args: ['build', '-t', 'gcr.io/dev-mlops/proxy-image', '-f', 'Dockerfile.proxy']
images: ['gcr.io/dev-mlops/proxy-image']

- name: 'gcr.io/cloud-builders/docker'
  id: docker-build-torchserve
  args: ['build', '-t', 'gcr.io/dev-mlops/torch-serve-image', '-f', 'Dockerfile.torchserve']
images: ['gcr.io/dev-mlops/torch-serve-image']

- name: gcr.io/cloud-builders/gcloud
  id: create-cluster
  entrypoint: 'bash'
  args:
  - -c
  - |
  - gcloud container clusters create
  - --zone=asia-northeast1
  - --no-enable-autoupgrade

- name: "gcr.io/cloud-builders/gke-deploy"
  args:
  - run
  - --filename=k8s
  - --location=asia-northeast1
  - --cluster=${_CLUSTER_NAME}
