version: '3'

services:
  proxy:
    container_name: proxy
    build:
      dockerfile: Dockerfile.proxy
      context: .
    restart: always
    volumes:
      - .:/app
    ports:
      - "8010:8010"
    depends_on:
      - torch-serve
    tty: true
 
  torch-serve:
    container_name: torch-serve
    build:
      dockerfile: Dockerfile.torchserve
      context: .
    restart: always
    volumes:
      - .:/torch-serve
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "7070:7070"
      - "7071:7071"
    tty: true

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
