version: '3'

services:
  torch-serve:
    container_name: torch-serve-test
    build:
      dockerfile: Dockerfile.torchserve
      context: .
    restart: always
    volumes:
      - .:/torch-serve
    ports:
      - "8080:8080"
      - "8081:8081"
      - "8083:8083"
      - "7070:7070"
      - "7071:7071"
    tty: true
