FROM python:3.9-slim

ENV APP_DIR /app
WORKDIR ${APP_DIR}
ARG REQUIREMENTS_TXT=requirements_proxy.txt

COPY ${REQUIREMENTS_TXT} ${APP_DIR}
COPY ./src ${APP_DIR}/src
COPY ./data ${APP_DIR}/data
COPY ./run.sh ${APP_DIR}/run.sh

RUN apt update && \
    pip install --upgrade pip && \
    pip install --no-cache-dir -r ${REQUIREMENTS_TXT}

COPY ./src/ ${APP_DIR}/src/

ENV PYTHONPATH /app

COPY ./run.sh ${APP_DIR}
RUN chmod +x ${APP_DIR}/run.sh
CMD ["./run.sh"]

